config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  root "posts#index"
  resources :posts, only: [:show, :index] do 
    resources :comments
  end
  resources :categories, only: :show

  namespace :admin do 
    resources :posts, except: [:index, :show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :posts, dependent: :destroy
    validates :name, :color, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :content, :user_id, :post_id, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  has_many :comments, dependent: :destroy
  validates :title, :summary, :body, :category, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :comments, dependent: :destroy
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
    before_action :authenticate_user!
    before_action :check_admin

    protected
    def check_admin
        redirect_to root_path, alert: "You are not admin." unless current_user.admin?
    end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::AdminController
  before_action :set_post, only: [:edit, :update, :destroy]


  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, success: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        flash.now[:danger] = "Post was not created."
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, success: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        flash.now[:danger] = "Post was not updated."
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, success: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :summary, :body, :image, :category_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    add_flash_types :danger, :success, :warning, :info
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :set_category, only: [:show]

    def show
        @posts = Post.where(category_id: @category.id).order(id: :desc).paginate(page: params[:page], per_page: 6)
    end

    private
      def set_category
        @category = Category.find(params[:id])
      end
  
  end
  

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_post, only: [:create, :destroy]

    def create
        @comment = @post.comments.new(comments_params)
        @comment.user_id = current_user.id
        unless @comment.save
            redirect_to @post, alert: "Comment was not created."
        else 
            redirect_to @post, alert: "Comment was successfully created."
        end
    end

    def destroy
        @comment = @post.comments.find(params[:id])
        if (@comment.user_id == current_user.id || current_user.admin?)
            @comment.destroy
            redirect_to @post, alert: "You successfully deleted the comment."
        else 
            redirect_to @post, alert: "You cannot delete the comment."
        end
    end
    
    private
      def set_post
        @post = Post.find(params[:post_id])
      end

      def comments_params
        params.require(:comment).permit(:id, :post_id, :user_id, :content)
      end 
  end
  

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: :show

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order(id: :desc).paginate(page: params[:page], per_page: 6)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    private
    def sign_up_params
      params.require(:user).permit(:username, :email, 
      :password, :password_confirmation)
    end
  
    def account_update_params
      params.require(:user).permit(:username, :email, 
      :password, :password_confirmation, :current_password)
    end
end  

app/helpers/application_helper.rb
module ApplicationHelper
    def bootstrap_class_for(name)
        {
            success: "alert-success",
            error: "alert-danger",
            danger: "alert-danger",
            alert: "alert-warning",
            notice: "alert-info"
        }[name.to_sym] || name 
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/posts/_form.html.erb
<%= form_for [:admin, @post], html: {multipart: true} do |form| %>
  <% if post.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h4>
      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control', maxlength: "70"  %>
  </div>

  <div class="form-group">
    <%= form.label :summary %>
    <%= form.text_area :summary, class: 'form-control', maxlength: "200"  %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class: 'form-control'  %>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.text_field :image, class: 'form-control'  %>
  </div>

  <div class="form-group">
    <%= form.label :category_id %>
    <%= form.collection_select :category_id, Category.order(:name), :id, :name, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit "Confirm", class: "btn btn-success btn-block" %>
  </div>
<% end %>

app/views/admin/posts/edit.html.erb
<h3 style="text-align: center">Editing post</h3>

<%= render 'form', post: @post %>

<div class="btn-group" style="margin: 0%; padding: 0%">
  <%= link_to 'Show', @post, class: "btn btn-primary" %> 
  <%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
  <%= link_to 'Back', posts_path, class: "btn btn-secondary" %>
</div>

app/views/admin/posts/new.html.erb
<h1>New post</h1>

<%= render 'form', post: @post %>
<%= link_to 'Back', posts_path, class: "btn btn-secondary" %>

app/views/categories/show.html.erb
<div class="row mb-2">
  <% @posts.each do |post| %>
    <div class="col-md-6">
      <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2" style="color: <%= post.category.color %>;"><%= post.category.name %></strong>
          <h3 class="mb-0 text" ><%= post.title %></h3>
          <div class="mb-1 text-muted"><%= post.created_at.to_date.strftime("%d %B, %Y") %></div>
          <p class="card-text mb-auto text" ><%= post.summary %></p>
          <span><%= link_to 'Continue reading', post %></span>
        </div>
      </div>
    </div> 
  <% end %>
</div>
<%= will_paginate @posts, renderer: 'BootstrapPaginationHelper::LinkRenderer' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
    <link rel="apple-touch-icon" href="/docs/4.4/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/4.4/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/4.4/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="manifest" href="/docs/4.4/assets/img/favicons/manifest.json">
    <link rel="mask-icon" href="/docs/4.4/assets/img/favicons/safari-pinned-tab.svg" color="#563d7c">
    <link rel="icon" href="/docs/4.4/assets/img/favicons/favicon.ico">
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <meta name="msapplication-config" content="/docs/4.4/assets/img/favicons/browserconfig.xml">
    <meta name="theme-color" content="#563d7c">
  </head>

  <body>
    <header class="blog-header py-3" style="padding: 1%">
        <div class="row flex-nowrap justify-content-between align-items-center">
          <div class="col-4 pt-1">
            <% if user_signed_in? && current_user.admin?%>
              <span class="text-muted"><%= link_to 'Create post', new_admin_post_path, class: "panel-link" %></span>
            <% end %>
          </div>
          <div class="col-4 text-center">
            <a class="blog-header-logo text-dark">MyBlog</a>
          </div>
          <div class="col-4 d-flex justify-content-end align-items-center">
            <% if user_signed_in? %>
              <a class="btn btn-sm btn-outline-primary" href="<%=  edit_user_registration_path %>" style="margin-right: 5px"> My account </a>
              <%= link_to " Exit ",  destroy_user_session_path, method: :delete, class: "btn btn-sm btn-outline-secondary"%>
            <% else %>
              <a class="btn btn-sm btn-outline-primary" href="<%=  new_user_registration_path %>">Sign up</a>
              <a class="btn btn-sm btn-outline-info" href="<%=  new_user_session_path %>" style="margin-left: 5px">Log in</a>
            <% end %>
          </div>
        </div>
    </header>
    <div class="container">
      <div class="nav-scroller py-1 mb-2">
        <nav class="nav d-flex justify-content-between">
          <span class="p-2 text-muted"><%= link_to 'All',  posts_path, class: "p-2 text-muted panel-link"%></span>
           <% Category.all.each do |category| %>
            <span class="p-2 text-muted"><%= link_to category.name, category, class: "p-2 text-muted panel-link" %></span>
          <% end %> 
        </nav>
      </div>
      <div class="row">
        <div class="col-md-12">
          <% flash.each do |name, message| %>
            <div class="alert <%= bootstrap_class_for(name) %>" role="alert">
              <button class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
              <%= message %>
            </div>
          <% end %>
        </div>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_comments.html.erb
<div class="card">

  <div class="card-header" ><h3> Comments </h3></div>

  <div class="card-body"  style="padding: 0%; margin: 0%;">
    <ul class="list-group">
      <% @post.comments.each do |comment| %>
          <div class="card bg-light" style="padding: 0%; margin: 0%;">
              <div class="card-body" style="padding: 0.5%; margin: 0%;">
                <div style="display: flex;">
                      <i><p class="card-title" style="font-size: 120%; font-weight: bold; padding-bottom: 0.2%; margin: 0%;">
                      from <%= User.find(comment.user_id).username %></p></i>
                      <% if User.find(comment.user_id).admin? %>
                        <span class="badge badge-pill badge-dark" style="margin-left: 0.5%">Admin</span>
                      <% end %>
                  </div>
                  <p class="card-text" style="padding: 0%; margin: 0%; margin-left: 0.5%"><%= comment.content %></p>
                  <% if (current_user!=nil && (comment.user_id == current_user.id || current_user.admin == true)) %>
                    <div style="text-align: right">
                      <%= link_to "Delete", post_comment_path(comment.post,comment), method: :delete, data:
                      {confirm:'Are you sure?'}%>
                    </div>
                  <% end %>
              </div>
          </div>
      <% end %>
    </ul>
  </div>
   
  <div class="card-footer">
    <div class="container">
      <%= form_for  [@post, @post.comments.build] do |form| %>
        <% if @post.errors.any?%>
          <div class="alert alert-danger">
            <h5><%= t('common.errors')%></h5>
            <ul>
              <%@post.comments.errors.full_messages.each do |msg|%>
                <li><%=msg%></li>
              <%end%>
            </ul>
          </div>
        <%end%>
        <div class="form-group">
          <%= form.label :content %>
          <%= form.text_field :content, class: 'form-control', maxlength: "350", minlength: "1"  %>
        </div>

        <div class="actions" style="text-align: right">
          <%= form.submit "Send", class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>

</div>

app/views/posts/index.html.erb
<div class="row mb-2">
  <% @posts.each do |post| %>
    <div class="col-md-6">
      <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2" style="color: <%= post.category.color %>;"><%= post.category.name %></strong>
          <h3 class="mb-0 text" ><%= post.title %></h3>
          <div class="mb-1 text-muted"><%= post.created_at.to_date.strftime("%d %B, %Y") %></div>
          <p class="card-text mb-auto text" ><%= post.summary %></p>
          <span><%= link_to 'Continue reading', post %></span>
        </div>
      </div>
    </div> 
  <% end %>
</div>
<%= will_paginate @posts, renderer: 'BootstrapPaginationHelper::LinkRenderer' %>

app/views/posts/show.html.erb
<div class="jumbotron p-4 p-md-5 text-dark rounded bg-light" style="margin: 0%; padding: 0%">
    <div class="col-md-6 px-0">
      <strong class="d-inline-block mb-2" style="color: <%= @post.category.color %>"><%= @post.category.name %></strong>
      <h1 class="display-4 font-italic text" style="margin-left: -1.5%;"><%= @post.title %></h1>
      <div class="mb-1 text-muted"><%= @post.created_at.to_date.strftime("%d %B, %Y") %></div>
      <h4 class="lead my-3 text"><%= @post.summary %></h4>
    </div>
    <div class="container">
      <p class="lead my-3 text" style="margin-left: -1.5%;"><%= @post.body %></p>
      <img class ="rounded mx-auto d-block" src="<%= @post.image %>" alt="" style="max-width: 100%"/>
    </div>
    <p class="lead mb-0" style="margin: 0.5%">by Tanya Lysak</p>
</div>
<div class="btn-group" style="margin: 0%; padding: 0%;">
  <% if user_signed_in? && current_user.admin? %>
    <%= link_to 'Edit', edit_admin_post_path(@post), class: "btn btn-warning" %>
    <%= link_to 'Destroy', admin_post_path(@post), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
  <% end %>
  <%= link_to 'Back', posts_path, class: "btn btn-secondary" %>
</div>
<%= render "comments", post: @post%>